import { Wand2, Boxes, Bell, Mail, Tag, Users } from "lucide-react";
import { Card } from "@/components/ui/Card";

const UPCOMING = [
  {
    icon: Wand2,
    title: "Fully arbitrary reports",
    description:
      "The agent will get a code-execution tool so it can compute and chart anything from your usage data -- not just today's fixed set of metrics and groupings.",
  },
  {
    icon: Boxes,
    title: "More provider connections",
    description:
      "Google Gemini, Amazon Bedrock, and Azure OpenAI, alongside the Anthropic and OpenAI keys you can connect today.",
  },
  {
    icon: Bell,
    title: "Budget alerts",
    description:
      "Set a monthly cap and get notified the moment you're on pace to blow past it, instead of finding out at the bill.",
  },
  {
    icon: Mail,
    title: "Scheduled digests",
    description:
      "A daily or weekly spend summary delivered by email, generated by the same agent that answers your questions today.",
  },
  {
    icon: Tag,
    title: "Cost allocation tags",
    description:
      "Tag usage by project, feature, or customer so spend can be sliced beyond just model and provider.",
  },
  {
    icon: Users,
    title: "Team workspaces",
    description:
      "Shared seats on one account with per-member visibility, instead of today's single-user login.",
  },
];

export function UpcomingFeatures() {
  return (
    <section className="mx-auto max-w-6xl px-6 pb-12">
      <h2 className="text-2xl font-semibold tracking-tight text-foreground">
        Upcoming features
      </h2>
      <div className="mt-8 grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-3">
        {UPCOMING.map((f) => (
          <Card key={f.title} className="border-dashed">
            <div className="flex items-start justify-between gap-2">
              <f.icon className="h-5 w-5 text-accent" aria-hidden />
              <span className="rounded-full bg-accent/10 px-2 py-0.5 text-xs font-medium text-accent">
                Coming soon
              </span>
            </div>
            <h3 className="mt-3 font-medium text-foreground">{f.title}</h3>
            <p className="mt-1 text-sm text-zinc-600 dark:text-zinc-400">{f.description}</p>
          </Card>
        ))}
      </div>
    </section>
  );
}
